[package]
name = "constella"
version = "0.1.0"
edition = "2018"
authors = ["Gryffon Bellish <owenbellish@gmail.com>"]

[dependencies]
structsy = "0.3"

[dependencies.twilight-model]
git = "https://github.com/twilight-rs/twilight.git"